### ISSUE TITLE
CI doesn't publish image with "latest" tag

### ISSUE THREAD

**Issue by trisberg** [projectriff/dev-utils#21]
Instructions use `--image=projectriff/dev-utils` but that pulls in an older image, looks like CI doesn't push a "latest" tag

**Comment by scothis** [comment]
this was intentional since previously only a `:latest` tag was published. Replacing that tag with a breaking change would break those users. At this point I think those uses have updated.

**Comment by trisberg** [comment]
ahh, ok, so we break new users ;) Might be time to make them update.
