### ISSUE TITLE
ERROR: EOF after subscribing to 2 streams

### ISSUE THREAD

**Issue by jldec** [projectriff/dev-utils#6]
Watching subscribed streams from 2 terminal sessions with `dev-utils kubectl exec` appears to fail after subscribing to a 2nd stream.

The `ERROR: EOF` appears in the first subscriber, when a 2nd one is added from a 2nd terminal session.

**Comment by sbawaska** [comment]
fixed via https://github.com/projectriff/dev-utils/commit/b3b90c3b8144633028029e62c6a4908dca06d2cf
